<?php
define("FS_BEND_01","Vue Rapide du Produit");
define("FS_BEND_02","Jarretières Optiques Insensibles aux Courbures</b>Réaliser les Meilleures Performances de Macrocourbures - Fournir la Largeur de Bande Supérieure pour les Centres de Données");
define("FS_BEND_03","EN SAVOIR PLUS");
define("FS_BEND_04","Solutions de Jarretières Optiques Monomodes Insensibles aux Courbures de FS.COM");
define("FS_BEND_05","Les jarretières optiques monomodes insensibles aux courbures de FS.COM avec un cœur de 9-microns sont la solution économique pour les applications où une faible perte de signal, une haute vitesse et des débits de données élevés sont nécessaires. Ils sont fabriqués avec des viroles en céramique durables et des gaines en PVC ou LSZH qui minimisent les dommages physiques au noyau et au revêtement. Chaque jarretière optique est 100% optiquement testée pour la perte d'insertion et la réflexion arrière. Ils sont disponibles dans les deux styles : simplex et duplex, avec des connecteurs de jarretières optiques LC, SC et ST pour répondre à tous les besoins d'installation. Choisissez les jarretières optiques monomodes insensibles aux courbures avec les connecteurs UPC, APC ou une combinaison des deux. Les options de couleur rendent le processus d'installation plus rapide et plus facile.");
define("FS_BEND_06","Câbles BIF OS2");
define("FS_BEND_07","Solutions de Jarretières Optiques Insensibles aux Courbures OM2 de FS.COM");
define("FS_BEND_08","Les jarretières optiques insensibles aux courbures OM2 de FS.COM sont conçus pour s'adapter aux espaces restreints et aux applications nécessitant une connexion d'angle non-standard. Ces jarretières optiques disposent des gaines en PVC ou OFNR (Riser évalué) avec les connecteurs LC, SC ou ST. Ces câbles utilisent des bottes flexibles spécialisés qui peuvent être pliées dans une variété d'angles. Pliez-les  à l'angle qui convient le mieux à votre application ! Nos jarretières optiques insensibles aux courbures OM2 sont fonctionnellement testés afin de garantir les meilleures performances avant la livraison. En utilisant les jarretières optiques insensibles aux courbures OM2 de FS.COM, la disponibilité du réseau critique est assurée. La personnalisation de longueur, les combinaisons de connecteurs et de polissages sont disponibles.");
define("FS_BEND_09","Solutions de Jarretières Optiques Insensibles aux Courbures OM3/OM4 de FS.COM");
define("FS_BEND_10","Les jarretières optiques insensibles aux courbures OM3/OM4 de FS.COM permettent un rayon de courbure de 7,5mm, ce qui est idéal pour les armoires de réseau SAN qui nécessitent 20 ou plusieurs coudes dans l'armoire ou les installations de haute densité avec des câbles entassés dans un très faible encombrement. Il offre la vitesse de transfert de données à 10 Gigabit dans des applications à largeur de bande élevée, 5 fois plus rapide que celle du câble à fibre optique de 50um standard. Fonctionner avec le laser VCSEL et les sources LED, nos jarretières optiques insensibles aux courbures OM3/OM4 sont 100% optiquement testées pour une performance maximale. Nous fournissons les câbles de toute longueur. Les connecteurs (LC, SC et ST) sont disponibles. Les deux connecteurs avec polissage APC et UPC sont  en stock, et les deux gaines de câbles PVC et LSZH peuvent être aussi fournies.");
define("FS_BEND_11","Câbles BIF OM3");
define("FS_BEND_12","Câbles BIF OM4");

?>