<?php

use Illuminate\Support\Facades\Route;

// 项目管理
Route::middleware('auth')->group(function () {

    // 诉求相关
    // 诉求标签管理
    Route::post('/labelCategories', 'Appeal\LabelCategoriesController@store')->name('labelCategories.store');
    Route::post('/labelCategories/sort', 'Appeal\LabelCategoriesController@sort')->name('labelCategories.sort');
    Route::patch('/labelCategories/{category}', 'Appeal\LabelCategoriesController@update')->name('labelCategories.update');
    Route::delete('/labelCategories/{category}', 'Appeal\LabelCategoriesController@destroy')->name('labelCategories.destroy');
    Route::get('/labelCategories', 'Appeal\LabelCategoriesController@index')->name('labelCategories.index.public');
    Route::get('/labelCategories/tree', 'Appeal\LabelCategoriesController@tree')->name('labelCategories.tree.public');
    Route::get('/labelCategories/{category}/labels', 'Appeal\LabelsController@index')->name('labelCategories.labels.index.public');
    Route::post('/labels', 'Appeal\LabelsController@store')->name('labels.store');
    Route::post('/labels/sort', 'Appeal\LabelsController@sort')->name('labels.sort');
    Route::patch('/labels/{label}', 'Appeal\LabelsController@update')->name('labels.update');
    Route::delete('/labels/{label}', 'Appeal\LabelsController@destroy')->name('labels.destroy');
    // 诉求管理
    Route::get('/appeals', 'Appeal\AppealsController@list')->name('appeals.list.public');
    Route::post('/appeals', 'Appeal\AppealsController@store')->name('appeals.store');
    Route::post('/appeals/createDemand', 'Appeal\AppealsController@createDemand')->name('appeals.createDemand.public');
    Route::get('/appeals/{appeal}/createDemand/cancel', 'Appeal\AppealsController@cancelDemand')->name('appeals.cancelDemand.public');
    Route::post('/appeals/{appeal}', 'Appeal\AppealsController@update')->name('appeals.update.public');
    Route::delete('/appeals/{appeal}', 'Appeal\AppealsController@delete')->name('appeals.delete.public');
    Route::post('/appeals/{appeal}/revocation', 'Appeal\AppealsController@revocation')->name('appeals.revocation.public');
    Route::get('/appeals/{appeal}/logs', 'Appeal\AppealsController@logs')->name('appeals.logs.public');
    Route::post('/appeals/{appeal}/labels', 'Appeal\AppealsController@labels')->name('appeals.labels.public');
    Route::delete('/appeals/{appeal}/labels/{label}', 'Appeal\AppealsController@deleteLabel')->name('appeals.deleteLabel.public');
    Route::get('/appeals/{appeal}/apply', 'Appeal\AppealsController@apply')->name('appeals.apply.public');
    Route::get('/appeals/{appeal}/apply/cancel', 'Appeal\AppealsController@applyCancel')->name('appeals.applyCancel.public');
    Route::post('/appeals/{appeal}/follow', 'Appeal\AppealsController@follow')->name('appeals.follow.public');
    Route::post('/appeals/{appeal}/products', 'Appeal\AppealsController@products')->name('appeals.products.public');
    Route::post('/appeals/{appeal}/verify', 'Appeal\AppealsController@verify')->name('appeals.verify.public');
    Route::post('/appeals/{appeal}/disassemble', 'Appeal\AppealsController@disassemble')->name('appeals.disassemble.public');
    Route::get('/appeals/{appeal}/details', 'Appeal\AppealsController@details')->name('appeals.details.public');
    Route::get('/appeals/{appeal}/principal', 'Appeal\AppealsController@principal')->name('appeals.principal.public');
    Route::post('/appeals/{appeal}/principal', 'Appeal\AppealsController@setPrincipal')->name('appeals.setPrincipal.public');
    Route::post('/appeals/{appeal}/attention', 'Appeal\AppealsController@attention')->name('appeals.attention.public');
    Route::patch('/appeals/transfer', 'Appeal\AppealsController@transfer')->name('appeals.transfer');

    // 产品
    Route::post('/products/lines', 'Product\ProductsController@store')->name('products.store');
    Route::post('/products/{product}/products', 'Product\ProductsController@addProducts')->name('products.addProducts');
    Route::patch('/products/sort', 'Product\ProductsController@sort')->name('products.sort');
    Route::post('/products/{product}/teams', 'Product\ProductsController@teams')->name('products.teams');
    Route::get('/products/{product}/teams', 'Product\ProductsController@getTeams')->name('products.getTeams.public');
    Route::get('/products/{product}/defaultDesignTeamMembers', 'Product\ProductsController@getDesignTeamMembers')->name('products.getDesignTeamMembers.public');
    Route::post('/products/{product}/members', 'Product\ProductsController@members')->name('products.members');
    Route::patch('/products/{product}/name', 'Product\ProductsController@name')->name('products.name');
    Route::patch('/products/{product}/description', 'Product\ProductsController@description')->name('products.description');
    Route::post('/products/{product}/modules', 'Product\ProductsController@modules')->name('products.modules');
    Route::patch('/products/{product}/modules', 'Product\ProductsController@modifyModules')->name('products.modifyModules');
    Route::post('/products/{product}/labels', 'Product\ProductsController@labels')->name('products.labels');
    Route::patch('/products/labels/{product}/name', 'Product\ProductsController@labelName')->name('products.labelName');
    Route::delete('/products/labels/{product}', 'Product\ProductsController@deleteLabel')->name('products.deleteLabel');
    Route::get('/products/{product}/logs', 'Product\ProductsController@statusLogs')->name('products.statusLogs.public');
    Route::patch('/products/{product}/status', 'Product\ProductsController@status')->name('products.status');
    Route::get('/products/tree', 'Product\ProductsController@tree')->name('products.tree.public');
    Route::get('/products/list', 'Product\ProductsController@list')->name('products.list.public');


    // 项目相关
    Route::post('/projects/{id}/attention', 'Project\ProjectController@attention')->name('projects.attention.public');
    Route::get('/projects/{id}/details', 'Project\ProjectController@details')->name('projects.details.public');
    Route::get('/projects', 'Project\ProjectController@index')->name('projects.list.public');
    Route::get('/projects/dynamicLog', 'Project\ProjectController@getDynamicLog')->name('projects.dynamicLogs.public');
    Route::get('/projects/{id}/logs', 'Project\ProjectController@getProjectLogs')->name('projects.logs.public');
    Route::post('projects/major', 'Project\ProjectController@createMajorProject')->name('projects.major');
    Route::post('projects/daily', 'Project\ProjectController@createDailyProject')->name('projects.daily');
    Route::post('/projects/{id}', 'Project\ProjectController@updateProject')->name('projects.edit.public');
    Route::post('/projects/{id}/status', 'Project\ProjectController@updateStatus')->name('projects.update.status.public');
    Route::get('/projects/statistics', 'Project\ProjectController@statistics')->name('projects.statistics.public');
    Route::post('/projects/{id}/projectSummary', 'Project\ProjectController@projectSummary')->name('projects.projectSummary.public');

    // 需求相关
    Route::post('/projects/demands/{id}/confirm', 'Project\DemandsController@confirmDemand')->name('projects.confirmDemand.public');
    Route::post('/projects/demands/batchConfirm', 'Project\DemandsController@batchConfirm')->name('projects.batchConfirmDemand.public');
    Route::post('/projects/demands/{id}/confirm/cancel', 'Project\DemandsController@cancelConfirm')->name('projects.cancelConfirm.public');
    Route::post('/projects/demands/{id}/push', 'Project\DemandsController@pushDemand')->name('projects.pushDemand.public');
    Route::post('/projects/demands/batchPush', 'Project\DemandsController@batchPushDemand')->name('projects.batchPushDemand.public');

    Route::post('/demands/{id}/pause', 'Demand\DemandController@pauseDemand')->name('demand.pauseDemand.public');
    Route::post('/demands/{id}/revocation', 'Demand\DemandController@revocationDemand')->name('demand.revocationDemand.public');
    Route::get('/demands/{id}/continue', 'Demand\DemandController@continueDemand')->name('demand.continueDemand.public');
    Route::get('/demands/{id}/details', 'Demand\DemandController@details')->name('demand.details.public');
    Route::post('/demands/{id}/verify', 'Demand\DemandController@verify')->name('demand.verify.public');
    Route::get('/demands/{id}/logs', 'Demand\DemandController@logs')->name('demand.logs.public');
    Route::get('/demands/{id}/test', 'Demand\DemandController@beginTest')->name('demand.test.public');
    Route::post('/demands/{id}/complete', 'Demand\DemandController@complete')->name('demand.complete.public');
    Route::post('/demands/{id}/priority', 'Demand\DemandController@priority')->name('demand.priority.public');
    Route::get('/demands/{id}/tasks', 'Demand\DemandController@tasks')->name('demand.tasks.public');
    Route::get('/demands', 'Demand\DemandController@list')->name('demand.list.public');
    Route::post('/demands', 'Demand\DemandController@store')->name('demand.create');
    Route::post('/demands/{id}', 'Demand\DemandController@updateDemand')->name('demand.update.public');
    Route::post('/demands/{id}/attention', 'Demand\DemandController@attention')->name('demand.attention.public');
    Route::post('/demands/{demand}/principal', 'Demand\DemandController@setPrincipal')->name('demands.setPrincipal.public');
    Route::get('/demands/{demand}/principal', 'Demand\DemandController@getPrincipal')->name('demands.getPrincipal.public');
    Route::patch('/demands/transfer', 'Demand\DemandController@transfer')->name('demand.transfer');

    // 任务相关
    // 设计任务
    Route::get('/tasks/design', 'Task\DesignTaskController@list')->name('tasks.design.list.public');
    Route::post('/tasks/design', 'Task\DesignTaskController@store')->name('tasks.design.store');
    Route::post('/tasks/design/{task}', 'Task\DesignTaskController@update')->name('tasks.design.update.public');
    Route::get('/tasks/design/{task}/details', 'Task\DesignTaskController@details')->name('tasks.design.details.public');
    Route::post('/tasks/design/{task}/priority', 'Task\DesignTaskController@priority')->name('tasks.design.priority.public');
    Route::post('/tasks/design/{task}/principal', 'Task\DesignTaskController@principal')->name('tasks.design.principal.public');
    Route::get('/tasks/design/{task}/principal', 'Task\DesignTaskController@getPrincipal')->name('tasks.design.getPrincipal.public');
    Route::post('/tasks/design/{task}/review', 'Task\DesignTaskController@review')->name('tasks.design.review.public');
    Route::post('/tasks/design/{task}/verify', 'Task\DesignTaskController@verify')->name('tasks.design.verify.public');
    Route::post('/tasks/design/{task}/sequence', 'Task\DesignTaskController@sequence')->name('tasks.design.sequence.public');
    Route::get('/tasks/design/{task}/logs', 'Task\DesignTaskController@logs')->name('tasks.design.logs.public');
    Route::post('/tasks/design/{task}/expirationDate', 'Task\DesignTaskController@expirationDate')->name('tasks.design.expirationDate.public');
    Route::post('/tasks/design/parts/{part}/handler', 'Task\DesignTaskController@partHandler')->name('tasks.design.parts.handler.public');
    Route::post('/tasks/design/parts/{part}/subtasks', 'Task\DesignTaskController@subTask')->name('tasks.design.parts.subtasks.public');
    Route::get('/tasks/design/parts/{part}/logs', 'Task\DesignTaskController@partLogs')->name('tasks.design.parts.logs.public');
    Route::post('/tasks/design/parts/subtasks/{subTask}/submit', 'Task\DesignTaskController@subTaskSubmit')->name('tasks.design.parts.subtasks.submit.public');
    Route::post('/tasks/design/parts/subtasks/{subTask}/submit/cancel', 'Task\DesignTaskController@subTaskSubmitCancel')->name('tasks.design.parts.subtasks.submit.cancel.public');
    Route::post('/tasks/design/parts/subtasks/{subTask}/submit/update', 'Task\DesignTaskController@subTaskSubmitUpdate')->name('tasks.design.parts.subtasks.submit.update.public');
    Route::post('/tasks/design/parts/subtasks/{subTask}/start', 'Task\DesignTaskController@subTaskStart')->name('tasks.design.parts.subtasks.start.public');
    Route::post('/tasks/design/parts/subtasks/{subTask}/pause', 'Task\DesignTaskController@subTaskPause')->name('tasks.design.parts.subtasks.pause.public');
    Route::post('/tasks/design/parts/subtasks/{subTask}/revocation', 'Task\DesignTaskController@subTaskRevocation')->name('tasks.design.parts.subtasks.revocation.public');
    Route::post('/tasks/design/parts/subtasks/{subTask}/complete', 'Task\DesignTaskController@subTaskComplete')->name('tasks.design.parts.subtasks.complete.public');
    Route::post('/tasks/design/parts/subtasks/{subTask}/expirationDate', 'Task\DesignTaskController@subTaskExpirationDate')->name('tasks.design.parts.subtasks.expirationDate.public');
    Route::post('/tasks/design/parts/subtasks/{subTask}/priority', 'Task\DesignTaskController@subTaskPriority')->name('tasks.design.parts.subtasks.priority.public');
    Route::get('/tasks/design/parts/subtasks/{subTask}/logs', 'Task\DesignTaskController@subTaskLogs')->name('tasks.design.parts.subtasks.logs.public');
    Route::post('/tasks/design/parts/subtasks/{subTask}/versions', 'Task\DesignTaskController@subTaskUpdateVersion')->name('tasks.design.parts.subtasks.versions.public');
    // 开发任务
    Route::get('/tasks/dev', 'Task\DevTaskController@list')->name('tasks.dev.list.public');
    Route::post('/tasks/dev', 'Task\DevTaskController@store')->name('tasks.dev.store');
    Route::post('/tasks/dev/{task}', 'Task\DevTaskController@update')->name('tasks.dev.update.public');
    Route::get('/tasks/dev/{task}/details', 'Task\DevTaskController@details')->name('tasks.dev.details.public');
    Route::post('/tasks/dev/{task}/priority', 'Task\DevTaskController@priority')->name('tasks.dev.priority.public');
    Route::get('/tasks/dev/{task}/principal', 'Task\DevTaskController@getPrincipal')->name('tasks.dev.getPrincipal.public');
    Route::post('/tasks/dev/{task}/principal', 'Task\DevTaskController@principal')->name('tasks.dev.principal.public');
    Route::get('/tasks/dev/{task}/logs', 'Task\DevTaskController@logs')->name('tasks.dev.logs.public');
    Route::post('/tasks/dev/{task}/expirationDate', 'Task\DevTaskController@expirationDate')->name('tasks.dev.expirationDate.public');
    Route::post('/tasks/dev/{task}/subtasks', 'Task\DevTaskController@subTask')->name('tasks.dev.subtasks.public');
    Route::post('/tasks/dev/{task}/handler', 'Task\DevTaskController@handler')->name('tasks.dev.handler.public');
    Route::post('/tasks/dev/{task}/verify', 'Task\DevTaskController@verify')->name('tasks.dev.verify.public');
    Route::patch('/tasks/dev/{task}/verify', 'Task\DevTaskController@verifyUpdate')->name('tasks.dev.verifyUpdate.public');
    Route::post('/tasks/dev/subtasks/{subTask}/start', 'Task\DevTaskController@subTaskStart')->name('tasks.dev.subtasks.start.public');
    Route::post('/tasks/dev/subtasks/{subTask}/submit', 'Task\DevTaskController@subTaskSubmit')->name('tasks.dev.subtasks.submit.public');
    Route::post('/tasks/dev/subtasks/{subTask}/submit/cancel', 'Task\DevTaskController@subTaskSubmitCancel')->name('tasks.dev.subtasks.submit.cancel.public');
    Route::post('/tasks/dev/subtasks/{subTask}/submit/update', 'Task\DevTaskController@subTaskSubmitUpdate')->name('tasks.dev.subtasks.submit.update.public');
    Route::post('/tasks/dev/subtasks/{subTask}/revocation', 'Task\DevTaskController@subTaskRevocation')->name('tasks.dev.subtasks.revocation.public');
    Route::post('/tasks/dev/subtasks/{subTask}/pause', 'Task\DevTaskController@subTaskPause')->name('tasks.dev.subtasks.pause.public');
    Route::post('/tasks/dev/subtasks/{subTask}/complete', 'Task\DevTaskController@subTaskComplete')->name('tasks.dev.subtasks.complete.public');
    Route::post('/tasks/dev/subtasks/{subTask}/expirationDate', 'Task\DevTaskController@subTaskExpirationDate')->name('tasks.dev.subtasks.expirationDate.public');
    Route::post('/tasks/dev/subtasks/{subTask}/priority', 'Task\DevTaskController@subTaskPriority')->name('tasks.dev.subtasks.priority.public');
    Route::get('/tasks/dev/subtasks/{subTask}/logs', 'Task\DevTaskController@subTaskLogs')->name('tasks.dev.subtasks.logs.public');
    Route::post('/tasks/dev/subtasks/{subTask}/versions', 'Task\DevTaskController@subTaskUpdateVersion')->name('tasks.dev.subtasks.versions.public');
    Route::get('/tasks/dev/workload', 'Task\DevTaskController@getWorkload')->name('tasks.dev.workload.public');
    Route::get('/tasks/dev/appraisalData', 'Task\DevTaskController@getAppraisalData')->name('tasks.dev.appraisalData.public');
    // 测试任务
    Route::get('/tasks/test', 'Task\TestTaskController@list')->name('tasks.test.list.public');
    Route::post('/tasks/test', 'Task\TestTaskController@store')->name('tasks.test.store');
    Route::post('/tasks/test/{task}', 'Task\TestTaskController@update')->name('tasks.test.update.public');
    Route::get('/tasks/test/{task}/details', 'Task\TestTaskController@details')->name('tasks.test.details.public');
    Route::post('/tasks/test/{task}/priority', 'Task\TestTaskController@priority')->name('tasks.test.priority.public');
    Route::get('/tasks/test/{task}/principal', 'Task\TestTaskController@getPrincipal')->name('tasks.test.getPrincipal.public');
    Route::post('/tasks/test/{task}/principal', 'Task\TestTaskController@principal')->name('tasks.test.principal.public');
    Route::get('/tasks/test/{task}/logs', 'Task\TestTaskController@logs')->name('tasks.test.logs.public');
    Route::post('/tasks/test/{task}/expirationDate', 'Task\TestTaskController@expirationDate')->name('tasks.test.expirationDate.public');
    Route::post('/tasks/test/{task}/subtasks', 'Task\TestTaskController@subTask')->name('tasks.test.subtasks.public');
    Route::post('/tasks/test/{task}/handler', 'Task\TestTaskController@handler')->name('tasks.test.handler.public');
    Route::post('/tasks/test/{task}/verify', 'Task\TestTaskController@verify')->name('tasks.test.verify.public');
    Route::patch('/tasks/test/{task}/verify', 'Task\TestTaskController@verifyUpdate')->name('tasks.test.verifyUpdate.public');
    Route::post('/tasks/test/subtasks/{subTask}/start', 'Task\TestTaskController@subTaskStart')->name('tasks.test.subtasks.start.public');
    Route::post('/tasks/test/subtasks/{subTask}/submit', 'Task\TestTaskController@subTaskSubmit')->name('tasks.test.subtasks.submit.public');
    Route::post('/tasks/test/subtasks/{subTask}/submit/cancel', 'Task\TestTaskController@subTaskSubmitCancel')->name('tasks.test.subtasks.submit.cancel.public');
    Route::post('/tasks/test/subtasks/{subTask}/submit/update', 'Task\TestTaskController@subTaskSubmitUpdate')->name('tasks.test.subtasks.submit.update.public');
    Route::post('/tasks/test/subtasks/{subTask}/revocation', 'Task\TestTaskController@subTaskRevocation')->name('tasks.test.subtasks.revocation.public');
    Route::post('/tasks/test/subtasks/{subTask}/pause', 'Task\TestTaskController@subTaskPause')->name('tasks.test.subtasks.pause.public');
    Route::post('/tasks/test/subtasks/{subTask}/complete', 'Task\TestTaskController@subTaskComplete')->name('tasks.test.subtasks.complete.public');
    Route::post('/tasks/test/subtasks/{subTask}/expirationDate', 'Task\TestTaskController@subTaskExpirationDate')->name('tasks.test.subtasks.expirationDate.public');
    Route::post('/tasks/test/subtasks/{subTask}/priority', 'Task\TestTaskController@subTaskPriority')->name('tasks.test.subtasks.priority.public');
    Route::get('/tasks/test/subtasks/{subTask}/logs', 'Task\TestTaskController@subTaskLogs')->name('tasks.test.subtasks.logs.public');
    // 前端开发任务
    Route::get('/tasks/frontend', 'Task\FrontendTaskController@list')->name('tasks.frontend.list.public');
    Route::post('/tasks/frontend', 'Task\FrontendTaskController@store')->name('tasks.frontend.store');
    Route::post('/tasks/frontend/{task}', 'Task\FrontendTaskController@update')->name('tasks.frontend.update.public');
    Route::get('/tasks/frontend/{task}/details', 'Task\FrontendTaskController@details')->name('tasks.frontend.details.public');
    Route::post('/tasks/frontend/{task}/priority', 'Task\FrontendTaskController@priority')->name('tasks.frontend.priority.public');
    Route::get('/tasks/frontend/{task}/principal', 'Task\FrontendTaskController@getPrincipal')->name('tasks.frontend.getPrincipal.public');
    Route::get('/tasks/frontend/{task}/logs', 'Task\FrontendTaskController@logs')->name('tasks.frontend.logs.public');
    Route::post('/tasks/frontend/{task}/expirationDate', 'Task\FrontendTaskController@expirationDate')->name('tasks.frontend.expirationDate.public');
    Route::post('/tasks/frontend/{task}/subtasks', 'Task\FrontendTaskController@subTask')->name('tasks.frontend.subtasks.public');
    Route::post('/tasks/frontend/{task}/handler', 'Task\FrontendTaskController@handler')->name('tasks.frontend.handler.public');
    Route::post('/tasks/frontend/{task}/verify', 'Task\FrontendTaskController@verify')->name('tasks.frontend.verify.public');
    Route::patch('/tasks/frontend/{task}/verify', 'Task\FrontendTaskController@verifyUpdate')->name('tasks.frontend.verifyUpdate.public');
    Route::post('/tasks/frontend/subtasks/{subTask}/start', 'Task\FrontendTaskController@subTaskStart')->name('tasks.frontend.subtasks.start.public');
    Route::post('/tasks/frontend/subtasks/{subTask}/submit', 'Task\FrontendTaskController@subTaskSubmit')->name('tasks.frontend.subtasks.submit.public');
    Route::post('/tasks/frontend/subtasks/{subTask}/submit/cancel', 'Task\FrontendTaskController@subTaskSubmitCancel')->name('tasks.frontend.subtasks.submit.cancel.public');
    Route::post('/tasks/frontend/subtasks/{subTask}/submit/update', 'Task\FrontendTaskController@subTaskSubmitUpdate')->name('tasks.frontend.subtasks.submit.update.public');
    Route::post('/tasks/frontend/subtasks/{subTask}/revocation', 'Task\FrontendTaskController@subTaskRevocation')->name('tasks.frontend.subtasks.revocation.public');
    Route::post('/tasks/frontend/subtasks/{subTask}/pause', 'Task\FrontendTaskController@subTaskPause')->name('tasks.frontend.subtasks.pause.public');
    Route::post('/tasks/frontend/subtasks/{subTask}/complete', 'Task\FrontendTaskController@subTaskComplete')->name('tasks.frontend.subtasks.complete.public');
    Route::post('/tasks/frontend/subtasks/{subTask}/expirationDate', 'Task\FrontendTaskController@subTaskExpirationDate')->name('tasks.frontend.subtasks.expirationDate.public');
    Route::post('/tasks/frontend/subtasks/{subTask}/priority', 'Task\FrontendTaskController@subTaskPriority')->name('tasks.frontend.subtasks.priority.public');
    Route::get('/tasks/frontend/subtasks/{subTask}/logs', 'Task\FrontendTaskController@subTaskLogs')->name('tasks.frontend.subtasks.logs.public');
    Route::post('/tasks/frontend/subtasks/{subTask}/versions', 'Task\FrontendTaskController@subTaskUpdateVersion')->name('tasks.frontend.subtasks.versions.public');
    // 移动端开发任务
    Route::get('/tasks/mobile', 'Task\MobileTaskController@list')->name('tasks.mobile.list.public');
    Route::post('/tasks/mobile', 'Task\MobileTaskController@store')->name('tasks.mobile.store');
    Route::post('/tasks/mobile/{task}', 'Task\MobileTaskController@update')->name('tasks.mobile.update.public');
    Route::get('/tasks/mobile/{task}/details', 'Task\MobileTaskController@details')->name('tasks.mobile.details.public');
    Route::post('/tasks/mobile/{task}/priority', 'Task\MobileTaskController@priority')->name('tasks.mobile.priority.public');
    Route::get('/tasks/mobile/{task}/principal', 'Task\MobileTaskController@getPrincipal')->name('tasks.mobile.getPrincipal.public');
    Route::get('/tasks/mobile/{task}/logs', 'Task\MobileTaskController@logs')->name('tasks.mobile.logs.public');
    Route::post('/tasks/mobile/{task}/expirationDate', 'Task\MobileTaskController@expirationDate')->name('tasks.mobile.expirationDate.public');
    Route::post('/tasks/mobile/{task}/subtasks', 'Task\MobileTaskController@subTask')->name('tasks.mobile.subtasks.public');
    Route::post('/tasks/mobile/{task}/handler', 'Task\MobileTaskController@handler')->name('tasks.mobile.handler.public');
    Route::post('/tasks/mobile/{task}/verify', 'Task\MobileTaskController@verify')->name('tasks.mobile.verify.public');
    Route::patch('/tasks/mobile/{task}/verify', 'Task\MobileTaskController@verifyUpdate')->name('tasks.mobile.verifyUpdate.public');
    Route::post('/tasks/mobile/subtasks/{subTask}/start', 'Task\MobileTaskController@subTaskStart')->name('tasks.mobile.subtasks.start.public');
    Route::post('/tasks/mobile/subtasks/{subTask}/submit', 'Task\MobileTaskController@subTaskSubmit')->name('tasks.mobile.subtasks.submit.public');
    Route::post('/tasks/mobile/subtasks/{subTask}/submit/cancel', 'Task\MobileTaskController@subTaskSubmitCancel')->name('tasks.mobile.subtasks.submit.cancel.public');
    Route::post('/tasks/mobile/subtasks/{subTask}/submit/update', 'Task\MobileTaskController@subTaskSubmitUpdate')->name('tasks.mobile.subtasks.submit.update.public');
    Route::post('/tasks/mobile/subtasks/{subTask}/revocation', 'Task\MobileTaskController@subTaskRevocation')->name('tasks.mobile.subtasks.revocation.public');
    Route::post('/tasks/mobile/subtasks/{subTask}/pause', 'Task\MobileTaskController@subTaskPause')->name('tasks.mobile.subtasks.pause.public');
    Route::post('/tasks/mobile/subtasks/{subTask}/complete', 'Task\MobileTaskController@subTaskComplete')->name('tasks.mobile.subtasks.complete.public');
    Route::post('/tasks/mobile/subtasks/{subTask}/expirationDate', 'Task\MobileTaskController@subTaskExpirationDate')->name('tasks.mobile.subtasks.expirationDate.public');
    Route::post('/tasks/mobile/subtasks/{subTask}/priority', 'Task\MobileTaskController@subTaskPriority')->name('tasks.mobile.subtasks.priority.public');
    Route::get('/tasks/mobile/subtasks/{subTask}/logs', 'Task\MobileTaskController@subTaskLogs')->name('tasks.mobile.subtasks.logs.public');
    Route::post('/tasks/mobile/subtasks/{subTask}/versions', 'Task\MobileTaskController@subTaskUpdateVersion')->name('tasks.mobile.subtasks.versions.public');

    // 下拉列表
    Route::get('/dropDown/appealPublisher', 'DropDown\DropDownUsersController@appealPublisher')->name('dropDown.appealPublisher.public');
    Route::get('/dropDown/projectPrincipal', 'DropDown\DropDownUsersController@projectPrincipal')->name('dropDown.projectPrincipal.public');
    Route::get('/dropDown/demandPublisher', 'DropDown\DropDownUsersController@demandPublisher')->name('dropDown.demandPublisher.public');
    Route::get('/dropDown/testTaskPublisher', 'DropDown\DropDownUsersController@testTaskPublisher')->name('dropDown.testTaskPublisher.public');
    Route::get('/dropDown/devTaskPublisher', 'DropDown\DropDownUsersController@devTaskPublisher')->name('dropDown.devTaskPublisher.public');
    Route::get('/dropDown/designTaskPublisher', 'DropDown\DropDownUsersController@designTaskPublisher')->name('dropDown.designTaskPublisher.public');
    Route::get('/dropDown/frontendTaskPublisher', 'DropDown\DropDownUsersController@frontendTaskPublisher')->name('dropDown.frontendTaskPublisher.public');
    Route::get('/dropDown/mobileTaskPublisher', 'DropDown\DropDownUsersController@mobileTaskPublisher')->name('dropDown.mobileTaskPublisher.public');
    Route::get('/dropDown/department', 'DropDown\DropDownUsersController@department')->name('dropDown.department.public');

    Route::get('/dropDown/productLine', 'DropDown\DropDownProductsController@productLine')->name('dropDown.productLine.public');
    Route::get('/dropDown/productName', 'DropDown\DropDownProductsController@productName')->name('dropDown.productName.public');
    Route::get('/dropDown/productModule', 'DropDown\DropDownProductsController@productModule')->name('dropDown.productModule.public');
    Route::get('/dropDown/moduleCategory', 'DropDown\DropDownProductsController@moduleCategory')->name('dropDown.moduleCategory.public');

    Route::get('/dropDown/designPrincipal', 'DropDown\DropDownTasksController@designPrincipal')->name('dropDown.designPrincipal.public');
    Route::get('/dropDown/productPrincipal', 'DropDown\DropDownTasksController@productPrincipal')->name('dropDown.productPrincipal.public');
    Route::get('/dropDown/devPrincipal', 'DropDown\DropDownTasksController@devPrincipal')->name('dropDown.devPrincipal.public');
    Route::get('/dropDown/testPrincipal', 'DropDown\DropDownTasksController@testPrincipal')->name('dropDown.testPrincipal.public');
    Route::get('/dropDown/productMember', 'DropDown\DropDownTasksController@productMember')->name('dropDown.productMember.public');
    Route::get('/dropDown/productFollower', 'DropDown\DropDownTasksController@productFollower')->name('dropDown.productFollower.public');
    Route::get('/dropDown/interactionPrincipal', 'DropDown\DropDownTasksController@interactionPrincipal')->name('dropDown.interactionPrincipal.public');
    Route::get('/dropDown/visionPrincipal', 'DropDown\DropDownTasksController@visionPrincipal')->name('dropDown.visionPrincipal.public');
    Route::get('/dropDown/frontEndPrincipal', 'DropDown\DropDownTasksController@frontEndPrincipal')->name('dropDown.frontEndPrincipal.public');
    Route::get('/dropDown/mobilePrincipal', 'DropDown\DropDownTasksController@mobilePrincipal')->name('dropDown.mobilePrincipal.public');
    Route::get('/dropDown/artistPrincipal', 'DropDown\DropDownTasksController@artistPrincipal')->name('dropDown.artistPrincipal.public');
    Route::get('/dropDown/systemDevUser', 'DropDown\DropDownTasksController@systemDevUser')->name('dropDown.systemDevUser.public');
    Route::get('/dropDown/designTaskHandler', 'DropDown\DropDownTasksController@designTaskHandler')->name('dropDown.designTaskHandler.public');
    Route::get('/dropDown/testTaskHandler', 'DropDown\DropDownTasksController@testTaskHandler')->name('dropDown.testTaskHandler.public');
    Route::get('/dropDown/devTaskHandler', 'DropDown\DropDownTasksController@devTaskHandler')->name('dropDown.devTaskHandler.public');
    Route::get('/dropDown/frontendTaskHandler', 'DropDown\DropDownTasksController@frontendTaskHandler')->name('dropDown.frontendTaskHandler.public');
    Route::get('/dropDown/mobileTaskHandler', 'DropDown\DropDownTasksController@mobileTaskHandler')->name('dropDown.mobileTaskHandler.public');
    Route::get('/excel/assessment/analysis', "Excel\ExcelDownloadController@assessmentAnalysis")->name('excel.assessment.analysis');

    Route::get('/dropDown/departmentUser', "DropDown\DropDownUsersController@getDepartmentUser")->name('dropDown.departmentUser.public');
    Route::get('/dropDown/demandList', 'DropDown\DemandsController@list')->name('dropDown.demandList.public');

    Route::get('/dropDown/bugs/programPrincipal', 'DropDown\BugsController@programPrincipal')->name('dropDown.bugs.programPrincipal.public');
    Route::get('/dropDown/bugs/follower', 'DropDown\BugsController@follower')->name('dropDown.bugs.follower.public');
    Route::get('/dropDown/bugs/productPrincipal', 'DropDown\BugsController@productPrincipal')->name('dropDown.bugs.productPrincipal.public');
    Route::get('/dropDown/bugs/testPrincipal', 'DropDown\BugsController@testPrincipal')->name('dropDown.bugs.testPrincipal.public');

    // bug 相关
    // 故障原因配置
    Route::post('/bugs/reason', 'Bug\BugsReasonController@store')->name('bugs.reason.store');
    Route::patch('/bugs/reason/{reason}', 'Bug\BugsReasonController@update')->name('bugs.reason.update');
    Route::delete('/bugs/reason/{reason}', 'Bug\BugsReasonController@delete')->name('bugs.reason.delete');
    Route::get('/bugs/reason', 'Bug\BugsReasonController@index')->name('bugs.reason.index.public');
    // 绑定负责人
    Route::post('/bugs/principal', 'Bug\BugsPrincipalController@batchBinding')->name('bugs.principal.batchBinding');
    Route::patch('/bugs/principal/{dept_id}', 'Bug\BugsPrincipalController@update')->name('bugs.principal.update');
    Route::get('/bugs/principal', 'Bug\BugsPrincipalController@index')->name('bugs.principal.index.public');
    // bugs相关
    Route::post('/bugs', 'Bug\BugsController@store')->name('bugs.store');
    Route::get('/bugs', 'Bug\BugsController@list')->name('bugs.list.public');
    Route::post('/bugs/{bug}', 'Bug\BugsController@update')->name('bugs.update.public');
    Route::get('/bugs/{bug}/detail', 'Bug\BugsController@detail')->name('bugs.detail.public');
    Route::get('/bugs/{bug}/logs', 'Bug\BugsController@logs')->name('bugs.logs.public');
    Route::get('/bugs/{bug}/examineLogs', 'Bug\BugsController@examineLogs')->name('bugs.examineLogs.public');
    Route::post('/bugs/{bug}/revocation', 'Bug\BugsController@revocation')->name('bugs.revocation.public');
    Route::post('/bugs/{bug}/productPrincipal', 'Bug\BugsController@productPrincipal')->name('bugs.productPrincipal.public');
    Route::post('/bugs/{bug}/testPrincipal', 'Bug\BugsController@testPrincipal')->name('bugs.testPrincipal.public');
    Route::post('/bugs/{bug}/programPrincipal', 'Bug\BugsController@programPrincipal')->name('bugs.programPrincipal.public');
    Route::get('/bugs/{bug}/applyExamine', 'Bug\BugsController@applyExamine')->name('bugs.applyExamine.public');
    Route::post('/bugs/{bug}/applyExamineCancel', 'Bug\BugsController@applyExamineCancel')->name('bugs.applyExamineCancel.public');
    Route::post('/bugs/{bug}/follow', 'Bug\BugsController@follow')->name('bugs.follow.public');
    Route::post('/bugs/{bug}/financeExamine', 'Bug\BugsController@financeExamine')->name('bugs.financeExamine');
    Route::post('/bugs/{bug}/internalControlExamine', 'Bug\BugsController@internalControlExamine')->name('bugs.internalControlExamine');
    Route::post('/bugs/{bug}/appendInfo', 'Bug\BugsController@appendInfo')->name('bugs.appendInfo.public');
    Route::post('/bugs/{bug}/close', 'Bug\BugsController@close')->name('bugs.close.public');
    Route::post('/bugs/{bug}/submitHandleResult', 'Bug\BugsController@submitHandleResult')->name('bugs.submitHandleResult.public');
    Route::post('/bugs/{bug}/submitHandleResult/cancel', 'Bug\BugsController@submitHandleResultCancel')->name('bugs.submitHandleResultCancel.public');
    Route::patch('/bugs/{bug}/submitHandleResult/update', 'Bug\BugsController@updateHandleResult')->name('bugs.updateHandleResult.public');
    Route::post('/bugs/{bug}/acceptProduct', 'Bug\BugsController@acceptProduct')->name('bugs.acceptProduct.public');
    Route::post('/bugs/{bug}/acceptTest', 'Bug\BugsController@acceptTest')->name('bugs.acceptTest.public');
    Route::post('/bugs/{bug}/acceptPromulgator', 'Bug\BugsController@acceptPromulgator')->name('bugs.acceptPromulgator.public');
    Route::post('/bugs/{bug}/reexamine', 'Bug\BugsController@reexamine')->name('bugs.reexamine.public');
    Route::post('/bugs/{bug}/expirationDate', 'Bug\BugsController@expirationDate')->name('bugs.expirationDate.public');
    Route::post('/bugs/{bug}/start', 'Bug\BugsController@start')->name('bugs.start.public');

    // 发版管理
    // 发版产品
    Route::get('/releaseProducts', 'Releases\ReleaseProductsController@list')->name('releaseProducts.list.public');
    Route::get('/releaseProducts/admins', 'Releases\ReleaseProductsController@admins')->name('releaseProducts.admins.public');
    Route::get('/releaseProducts/statistics', 'Releases\ReleaseProductsController@statistics')->name('releaseProducts.statistics.public');
    Route::post('/releaseProducts', 'Releases\ReleaseProductsController@store')->name('releaseProducts.store');
    Route::patch('/releaseProducts/{releaseProduct}', 'Releases\ReleaseProductsController@update')->name('releaseProducts.update');
    Route::delete('/releaseProducts/{releaseProduct}', 'Releases\ReleaseProductsController@delete')->name('releaseProducts.delete');
    Route::post('/releaseProducts/{releaseProduct}/status', 'Releases\ReleaseProductsController@status')->name('releaseProducts.status');
    Route::get('/releaseProducts/{releaseProduct}/details', 'Releases\ReleaseProductsController@details')->name('releaseProducts.details.public');
    Route::get('/releaseProducts/{releaseProduct}/logs', 'Releases\ReleaseProductsController@logs')->name('releaseProducts.logs.public');
    Route::post('/releaseProducts/{releaseProduct}/versions', 'Releases\ReleaseProductsController@addVersions')->name('releaseProducts.addVersions.public');
    Route::get('/releaseProducts/{releaseProduct}/versions', 'Releases\ReleaseProductsController@versionList')->name('releaseProducts.versionList.public');
    // 版本号
    Route::patch('/releaseVersions/{releaseVersion}', 'Releases\ReleaseVersionsController@update')->name('releaseVersions.update.public');
    Route::delete('/releaseVersions/{releaseVersion}', 'Releases\ReleaseVersionsController@delete')->name('releaseVersions.delete.public');
    Route::get('/releaseVersions/{releaseVersion}/logs', 'Releases\ReleaseVersionsController@logs')->name('releaseVersions.logs.public');
    Route::post('/releaseVersions/{releaseVersion}/test', 'Releases\ReleaseVersionsController@releaseTest')->name('releaseVersions.releaseTest.public');
    Route::post('/releaseVersions/{releaseVersion}/online', 'Releases\ReleaseVersionsController@releaseOnline')->name('releaseVersions.releaseOnline.public');
    Route::get('/products/releaseVersions', 'Releases\ReleaseVersionsController@getVersionsByProduct')->name('products.releaseVersions.public');
    Route::get('/releaseVersions/{releaseVersion}/features', 'Releases\ReleaseVersionsController@features')->name('releaseVersions.features.public');
    Route::patch('/releaseVersions/feature/{id}', 'Releases\ReleaseVersionsController@modifyVersion')->name('releaseVersions.modifyVersion.public');
    Route::get('/releaseVersions/feature/{id}/confirm', 'Releases\ReleaseVersionsController@confirmVersion')->name('releaseVersions.confirmVersion.public');
    Route::get('/releaseVersions/feature/{id}/confirm/cancel', 'Releases\ReleaseVersionsController@cancelConfirmVersion')->name('releaseVersions.cancelConfirmVersion.public');
    Route::get('/releaseVersions/feature/productPublisher', 'Releases\ReleaseVersionsController@productPublisher')->name('releaseVersions.productPublisher.public');
    Route::get('/releaseVersions/feature/{id}/releaseTest', 'Releases\ReleaseVersionsController@taskReleaseTest')->name('releaseVersions.taskReleaseTest.public');
});

// 导出
Route::any('/projects/export', 'Project\ProjectController@export')->name('projects.export.public');
Route::any('/appeals/export', 'Appeal\AppealsController@exportExcel')->name('appeals.export.public');
Route::any('/demands/export', 'Demand\DemandController@exportExcel')->name('demands.export.public');
Route::any('/tasks/design/export', 'Task\DesignTaskController@exportExcel')->name('tasks.design.export.public');
Route::any('/tasks/dev/export', 'Task\DevTaskController@exportExcel')->name('tasks.dev.export.public');
Route::any('/tasks/test/export', 'Task\TestTaskController@exportExcel')->name('tasks.test.export.public');
Route::any('/bugs/export', 'Bug\BugsController@export')->name('bugs.export.public');
Route::middleware('auth.temp')->group(function () {
    Route::any('/releaseVersions/{releaseVersion}/features/export', 'Releases\ReleaseVersionsController@featureExport')->name('releaseVersions.featureExport.public');
    Route::any('/tasks/frontend/export', 'Task\FrontendTaskController@exportExcel')->name('tasks.frontend.export.public');
    Route::any('/tasks/mobile/export', 'Task\MobileTaskController@exportExcel')->name('tasks.mobile.export.public');
});
