stages:
  - release
  - production
  - local

# release 预发布
deploy_release:
  stage: release
  only:
    - release
  script:
    - which php
    - which composer
    - date
    - whoami
    - cd /data/wwwroot/uums-server
    - git pull origin release
    - composer dump-autoload
    - php artisan config:clear
    - php artisan route:clear
    - composer install
    - php artisan migrate
    - php artisan db:seed --class=PermissionsTableSeeder
    - php artisan db:seed --class=PageSeeder
    - php artisan permission:update-group
    - php artisan config:cache
    - php artisan event:cache
    - php artisan route:cache
    - php artisan optimize
    - date
  tags:
    - uums
    - server
    - release

# AWS 生产版本
deploy_production_aws:
  stage: production
  only:
    - master
  script:
    - date
    - whoami
    - cd /data/wwwroot/uums-server
    - $(which php) artisan down --message="代码维护中，请 10 秒后再试。"
    - $(which php) artisan config:clear
    - $(which php) artisan route:clear
    - git pull origin master
    - ./deploy.sh
    - $(which php) artisan permission:update-group
    - $(which php) artisan config:cache
    - $(which php) artisan event:cache
    - $(which php) artisan route:cache
    - $(which php) artisan up
  tags:
    - uums
    - server
    - production

# local 本地联调
deploy_local:
  stage: local
  only:
    - local
  script:
    - which php
    - which composer
    - date
    - whoami
    - cd /data/wwwroot/pm/uums-server
    - git pull origin local
    - composer dump-autoload
    - php artisan config:clear
    - php artisan route:clear
    - composer install
    - php artisan migrate
    - php artisan db:seed --class=PermissionsTableSeeder
    - php artisan db:seed --class=PageSeeder
    - php artisan permission:update-group
    - php artisan config:cache
    - php artisan event:cache
    - php artisan route:cache
    - php artisan optimize
    - date
  tags:
    - uums
    - server
    - local