<?php


namespace Modules\Base\Entities\Company;


use Illuminate\Support\Facades\Storage;
use Modules\Base\Entities\Model;

class CompanyMedia extends Model
{

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        self::deleted(function ($media){
            $path = $media->path;
            Storage::disk('base')->delete($path);
        });
    }

    protected $table = "company_media";

    protected $fillable = ['uuid', 'admin_name', 'admin_uuid', 'name', 'path', 'size', 'created_at', 'updated_at','uuid', 'model_uuid', 'model_type'];

    public function logAble()
    {
        return $this->morphTo('model', 'model_type' , 'model_uuid', 'uuid');
    }
}
