<?php
define('FS_DE_POLICY', '30 Tage Rückgaberecht');
define('FS_POLICY_TXT', 'Sind Sie mit Ihrem Produkt von FS.COM nicht zufrieden, können Sie den Artikel innerhalb von 30 Tagen nach Erhalt der Ware zurücksenden. ');
define('FS_DE_POLICY_TIT', 'Rückgaberecht mit 30 Tage Zufriedenheitsgarantie');
define('FS_DE_POLICY_TXT', 'FS.COM garantiert für alle seine Produkte erstklassige Qualität. Sollten unsere Kunden wider Erwarten nicht zufrieden sein, können bei FS.COM gekaufte Produkte an uns zurückgegeben werden. Das Rückgaberecht von FS.COM ermöglicht es Kunden, Artikel innerhalb von 30 Tagen ab Erhalt der Ware zurückzusenden. Wir erstatten entweder den Kaufpreis oder der Kunde erhält auf Wunsch einen Warenersatz, vorausgesetzt, der Arikel befindet sich bei FS.COM auf Lager');
define('FS_DE_POLICY_TITLE', 'Gehen Sie bitte folgendermaßen vor, um einen Artikel zurückzusenden:');
define('FS_DE_POLICY_DL1', '1. RMA (Rücksendenummer) beantragen');
define('FS_DE_POLICY_DL2', '2. RMA ausdrucken und Ware verpacken');
define('FS_DE_POLICY_DL3', '3. Rücksendeetikett beilegen');
define('FS_DE_POLICY_DL4', '4. Produkt zurückschicken');
define('FS_DE_POLICY_01', 'Alle Rücksendungen erfordern eine Rücksendenummer (RMA). Es gibt zwei Möglichkeiten, eine RMA-Nummer zu erhalten.');
define('FS_DE_POLICY_02', '1. Folgen Sie den unten aufgeführten Schritten um eine Rücksendeanfrage in "Mein Konto" zu erstellen und abzuschicken. Diese Methode ist am schnellsten.');
define('FS_DE_POLICY_03', 'Stellen Sie sicher, dass Sie bereits ein Konto auf der FS.COM-Webseite erstellt haben und dass die Artikel, die Sie zurückgeben möchten, über dieses Konto bestellt wurden.');
define('FS_DE_POLICY_04', 'Melden Sie sich bei Ihrem Konto an und gehen Sie in den Abschnitt "Meine Bestellungen". Dort suchen Sie bitte die Bestellung, die den Artikel enthält, und die entsprechende Bestellnummer.');
define('FS_DE_POLICY_05', 'Klicken Sie auf die Schaltfläche "Rückgabe/Umtausch" und folgen dann den Anweisungen während der gesamten Prozedur.');
define('FS_DE_POLICY_06', 'Sobald Sie eine Rücksendenummer (RMA) erhalten haben, gehen Sie in den RMA-Abschnitt der Webseite, um den Status Ihrer RMA-Anforderung zu verfolgen. Wenn der Status "genehmigt" lautet, können Sie den Artikel gemäß den Anweisungen bei "Track Status" zurückgeben.');
define('FS_DE_POLICY_07', '2.Sie können auch auf "');
define('FS_DE_POLICY_08', 'Produktrückgabeformular');
define('FS_DE_POLICY_09', '" gehen und dort Ihre Anfrage um Warenrückgabe an uns schicken. Sie erhalten innerhalb von 24 Stunden eine Antwort.');
define('FS_DE_POLICY_10', 'Bitte beachten Sie: ');
define('FS_DE_POLICY_11', 'RMA-Nummern sind nur bis zu 30 Tage nach Ausstellung gültig und können nicht verlängert oder neu vergeben werden. ');
define('FS_DE_POLICY_12', 'Bei der Rücksendung von defekten Produkten setzen Sie sich am besten mit einem Sales-Agenten in Verbindung, der Ihnen ein Versandetikett zusendet oder mit Ihnen einen Abholtermin vereinbart bzw. ein Prepaid-Versandetikett zur Verfügung stellt. ');
define('FS_DE_POLICY_13', 'Sämtliche Produkte von FS.COM (ausgenommen Sonderanfertigungen und Sonderverpackungen) können Sie innerhalb von 30 Tagen ab Erhalt der Ware an uns zurücksenden. FS.COM behält sich das Recht vor, Produktrücksendungen auch nach mehr als 30 Tagen zu akzeptieren.');
define('FS_DE_POLICY_14', 'Sonderanfertigungen können weder storniert noch zurückgeschickt werden. FS.COM behält sich das Recht vor, Rücksendungen trotzdem zu akzeptieren. ');
define('FS_DE_POLICY_15', 'In einigen Fällen benötigen wir zusätzliche Angaben von Ihnen, um Ihre Rücknahmeanfrage zu überprüfen. Sie erhalten dann innerhalb von 24 Stunden eine E-Mail.');
define('FS_DE_POLICY_16', 'Grundlegendes Rückgaberecht');
define('FS_DE_POLICY_17', 'Für alle defekte Produkte, die Sie bei FS.COM gekauft haben, bieten wir Ihnen die Rückgabe der Ware bei vollständiger Rückerstattung des Warenwertes beziehungsweise Umtausch oder Reperatur an; Für FS.COM-Produkte in neuem oder fast neuem Zustand, die sich auf Lager befinden, erstatten wir Ihnen alle Artikel oder wir bieten Ihnen Ersatz innerhalb von 30 Tagen an. Es ist nicht notwendig, die Artikel an uns zurückzuschicken, ausgenommen, Sie wurden falsch verwendet oder es entstanden Folgeschäden aufgrund falscher Verwendung. Alle Produkte müssen sauber, unbeschädigt und komplett mit allen Handbüchern, Zubehör, Papieren und Verpackungen zurückgeschickt werden. Die Artikel müssen in einem wiederverkaufbaren Zustand sein, frei von nichtentfernbaren Etiketten und weder Produkt noch Verpackung dürfen beschriftet sein. Die Rücksendung muss eine Kopie der Originalrechnung oder des Packzettels sowie eine entsprechend ausgefüllte RMA-Formularkopie enthalten. Für Artikel, die an uns zurückgeschickt werden und diese Voraussetzungen nicht erfüllen, werden zusätzliche Gebühren berechnet oder nicht als Rücksendung akzeptiert. In diesem Fall setzen wir uns mit Ihnen in Verbindung, um festzulegen, wie diese Artikel entsorgt werden können.');
define('FS_DE_POLICY_18', 'Sonderanfertigungen, Sonderverpackungen und Sonderanfertigungen in gutem Zustand können nicht storniert oder zurückgegeben werden. FS.COM behält sich das Recht vor, diese Rückgaben trotzdem zu akzeptieren. Alle Produkte sind in Verarbeitung und Ausführung garantiert frei von Mängel, aber wir können nicht jede Anwendung garantieren. Hat der Kunde uns Konfigurationen vorgelegt, garantieren wir, dass der Artikel gemäß der gelieferten Spezifikation
konstruiert wurde. Scheinbar defekte Artikel werden nach unserem Ermessen ersetzt oder repariert. Sonderanfertigen, die nicht ordnungsgemäß bestellt wurden, können zur  Nachbesserung für eine Lagerauffüllungsgebühr in Höhe von 25% bis 30%, die von FS.COM festgelegt wird, zurückgeschickt werden. Bitte beachten Sie, dass die Rückgabe dieser Artikel unserem Produktionsplan unterliegt, für die sofortige Reparatur oder dem sofortigen Austausch können Zusatzgebühren anfallen.');
define('FS_DE_POLICY_19', 'Von FS.COM hergestellte Artikel können zurückgegeben werden. Allerdings müssen die Bedingungen für die Rückgabe von Artikel sowie die notwendige Verpackung genau beachtet werden. Von FS.COM hergestellte Artikel in gutem Zustand unterliegen möglicherweise einer Lagergebühr, wenn sie zurückgeschickt werden.');
define('FS_DE_POLICY_20','Jedes Produkt, das elektronische Bauteile enthält, kann nicht an uns zurückgeschickt werden, ausgenommen bei Herstellerfehler. Die an uns zurückgeschickten Produkte werden von uns analysiert, ehe wir bestätigen können, dass sie gemäß unserer Warenrücksenderegelung (RMA) an uns zurückgeschickt werden können.');
define('FS_DE_POLICY_21', 'FS.COM behält sich das Recht vor, Produktrücksendungen 30 Tage nach Lieferung in Ausnahmefällen anzunehmen. Bitte kontaktieren Sie uns vorab, wenn Sie Artikel 30 Tage nach Lieferung zurückgeben möchten.');
define('FS_DE_POLICY_22', 'Bearbeitungszeit für Rückgaben');
define('FS_DE_POLICY_23', 'Rückerstattungen werden innerhalb von 7 Tagen bearbeitet, nachdem die Ware an uns zurückgeschickt wurde. Sie erhalten eine Gutschrift auf Ihre ursprüngliche Zahlungsmethode. Die Gutschrift wird auf Ihrem nächsten Auszug ausgewiesen, abhängig von der ausstellenden Bank und dem Abrechnungszyklus. Nach Abwicklung der Rückgabe erhalten Sie von uns eine E-Mail. Wir erstatten keine Versandkosten, ausgenommen wir haben falsche oder defekte Artikel verschickt.');
define('FS_DE_POLICY_24', 'RepEin Umtausch wird in der Regel nach Erhalt der zurückgeschickten Ware bearbeitet. Für Artikel, die auf Lager sind, erhalten Sie innerhalb von 1 bis 3 Werktagen einen Ersatz. Bei Artikel, die nicht auf Lager sind, hängt es von Herstellungszeit und Produkttests ab, Ihnen Ersatz zu beschaffen, aber wir tun unser Bestes, Ihnen innerhalb von einer Woche für Ersatz zu sorgen. In Fällen, bei denen Sie sofort Ersatz benötigen, wenden Sie sich bitte direkt mit der Tracking-Nummer der zurückgeschickten Ware an Ihren FS.COM-Verkaufsspezialisten, wir werden einen Ersatz vorbereiten, ehe das Paket in unserem Lager angekommen ist. Sobald das an uns zurückgeschickte Paket in unserem Lager angekommen ist, werden wir den Ersatzartikel an Sie ausliefern. Wir können gegen Gebühr auch einen parallele Warenumtausch anbieten, Sie erhalten die Gebühr nach Eingang der ursprünglichen Warenlieferung an uns wieder erstattet.');
define('FS_DE_POLICY_25', 'Eine Warenrückgabe zur Reparatur hängt vom Außmaß der Beschädigung des Artikels ab. Falls Sie sich entschließen, eine Ware zur Reparatur zurückzugeben, kontaktieren Sie uns bitte per E-Mail an ');
define('FS_DE_POLICY_26', 'legal@fs.com');
define('FS_DE_POLICY_27', ' oder rufen Sie uns an und schildern uns im Detail, warum Sie einen Artikel zurückgeben wollen. Wir prüfen, wie lange die Bearbeitungszeit sein wird und ob zusätzliche Kosten anfallen.');
define('FS_DE_POLICY_28', '*Bitte beachten Sie, dass es zu Stoßzeiten oder an Feiertagen zu kurzfristigen Verzögernungen kommen kann. Sie sind herzlich willkommen, uns bei allen Fragen zu kontaktieren. ');

?>