stages:
  - release
  - production
  - local

# release 预发布
deploy_release:
  stage: release
  only:
    - release
  script:
    - which yarn
    - date
    - whoami
    - cd /data/wwwroot/uums-client
    - git pull origin release
    - yarn install
    - yarn run build
    - rm -rf ../uums
    - cp -R ./dist ../uums
    - date
  tags:
    - uums
    - client
    - release

# 新加坡生产版本
deploy_production_sg:
  stage: production
  only:
    - master
  script:
    - date
    - whoami
    - cd /data/wwwroot/uums-client
    - git pull origin master
    - yarn install
    - yarn run build
    - rm -rf ./uums
    - cp -R ./dist ./uums
    - date
  tags:
    - uums
    - client
    - production
    - aliyun_sg
    
# local 本地开发
deploy_project_manage:
  stage: local
  only:
    - local
  script:
    - date
    - whoami
    - cd /data/wwwroot/pm/uums-client/
    - git pull origin local
    - yarn install
    - yarn run build
    - rm -rf ../uums
    - cp -R ./dist ../uums
    - date
  tags:
    - uums
    - client
    - local

# 国内生产版本
deploy_production_sz:
  stage: production
  only:
  - master
  script:
  - date
  - whoami
  - cd /data/wwwroot/uums-client
  - git pull origin master
  - yarn install
  - yarn run build
  - rm -rf ./uums
  - cp -R ./dist ./uums
  - date
  tags:
  - uums
  - client
  - production
  - aliyun_sz
