 <?php


 $mark_default = array(
                    array('rel' => 'alternate', 'hreflang' => 'x-default', 'href' => 'https://www.fs.com'),
                    array('rel' => 'alternate', 'hreflang' => 'en', 'href' => 'https://www.fs.com'),
                    array('rel' => 'alternate', 'hreflang' => 'en-GB', 'href' => 'https://www.fs.com/uk'),
                    array('rel' => 'alternate', 'hreflang' => 'en-AU', 'href' => 'https://www.fs.com/au'),
                    array('rel' => 'alternate', 'hreflang' => 'es', 'href' => 'https://www.fs.com/mx'),
                    array('rel' => 'alternate', 'hreflang' => 'en-SG', 'href' => 'https://www.fs.com/sg'),
                    array('rel' => 'alternate', 'hreflang' => 'ja-JP', 'href' => 'https://www.fs.com/jp'),
                    array('rel' => 'alternate', 'hreflang' => 'ru', 'href' => 'https://www.fs.com/ru'),
                    array('rel' => 'alternate', 'hreflang' => 'de', 'href' => 'https://www.fs.com/de'),
                    array('rel' => 'alternate', 'hreflang' => 'fr', 'href' => 'https://www.fs.com/fr'),
                    array('rel' => 'alternate', 'hreflang' => 'es-ES', 'href' => 'https://www.fs.com/es'),
                    array('rel' => 'alternate', 'hreflang' => 'en-DE', 'href' => 'https://www.fs.com/de-en'),
                    array('rel' => 'alternate', 'hreflang' => 'en-NL', 'href' => 'https://www.fs.com/de-en'),
                    array('rel' => 'alternate', 'hreflang' => 'en-IT', 'href' => 'https://www.fs.com/de-en'),
                    array('rel' => 'alternate', 'hreflang' => 'en-SE', 'href' => 'https://www.fs.com/de-en'),
                    array('rel' => 'alternate', 'hreflang' => 'en-PL', 'href' => 'https://www.fs.com/de-en'),
                    array('rel' => 'alternate', 'hreflang' => 'en-DK', 'href' => 'https://www.fs.com/de-en'),
                    array('rel' => 'alternate', 'hreflang' => 'en-AT', 'href' => 'https://www.fs.com/de-en'),
                    array('rel' => 'alternate', 'hreflang' => 'en-NO', 'href' => 'https://www.fs.com/de-en'),
                    array('rel' => 'alternate', 'hreflang' => 'en-IE', 'href' => 'https://www.fs.com/de-en'),
                    array('rel' => 'alternate', 'hreflang' => 'en-RO', 'href' => 'https://www.fs.com/de-en'),
                    array('rel' => 'alternate', 'hreflang' => 'en-CZ', 'href' => 'https://www.fs.com/de-en'),
                    array('rel' => 'alternate', 'hreflang' => 'en-FI', 'href' => 'https://www.fs.com/de-en'),
                    array('rel' => 'alternate', 'hreflang' => 'en-PT', 'href' => 'https://www.fs.com/de-en'),
                    array('rel' => 'alternate', 'hreflang' => 'en-GR', 'href' => 'https://www.fs.com/de-en'),
                    array('rel' => 'alternate', 'hreflang' => 'en-HU', 'href' => 'https://www.fs.com/de-en'),
                    array('rel' => 'alternate', 'hreflang' => 'en-BG', 'href' => 'https://www.fs.com/de-en'),
                    array('rel' => 'alternate', 'hreflang' => 'en-SK', 'href' => 'https://www.fs.com/de-en'),
                    array('rel' => 'alternate', 'hreflang' => 'en-RS', 'href' => 'https://www.fs.com/de-en'),
                    array('rel' => 'alternate', 'hreflang' => 'en-LT', 'href' => 'https://www.fs.com/de-en'),
                    array('rel' => 'alternate', 'hreflang' => 'en-HR', 'href' => 'https://www.fs.com/de-en'),
                    array('rel' => 'alternate', 'hreflang' => 'en-SI', 'href' => 'https://www.fs.com/de-en'),
                    array('rel' => 'alternate', 'hreflang' => 'en-LV', 'href' => 'https://www.fs.com/de-en'),
                    array('rel' => 'alternate', 'hreflang' => 'en-EE', 'href' => 'https://www.fs.com/de-en'),
                    array('rel' => 'alternate', 'hreflang' => 'en-MD', 'href' => 'https://www.fs.com/de-en'),
                    array('rel' => 'alternate', 'hreflang' => 'en-MT', 'href' => 'https://www.fs.com/de-en'),
                    array('rel' => 'alternate', 'hreflang' => 'en-AL', 'href' => 'https://www.fs.com/de-en'),
                    array('rel' => 'alternate', 'hreflang' => 'en-BA', 'href' => 'https://www.fs.com/de-en'),
                    array('rel' => 'alternate', 'hreflang' => 'en-IS', 'href' => 'https://www.fs.com/de-en'),
                );
?>